---
title: "Fifa"
author: "Rodrigo Valdes Ortiz"
date: "2018"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: cerulean
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# library(shiny)
library(htmltools)
library(RColorBrewer)
library(data.table)
library(ggplot2)

# library(shinythemes)

# fluidPage(theme = shinytheme("cerulean"))

options(digits = 3)
```


```{r echo=FALSE}
# Main theme
blank_theme <- theme_minimal()+
  theme(
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )
```

```{r echo=FALSE}
get_year <- function(df, num_compare) {
  aux1 = df[df$letality==num_compare, ]
  aux2 = aux1[complete.cases(aux1), ]
  aux3 = as.integer(aux2$year)[1]
}
```

```{r echo=FALSE}
get_date <- function(df, num_compare) {
  aux1 = df[df$let_game==num_compare, ]
  aux2 = aux1[complete.cases(aux1), ]
  aux3 = as.integer(aux2$date)[1]
}
```


```{r echo=FALSE}
resultsAll <- reactive({
  results_all <- fread("output/results_all.csv")
  
})
```


```{r echo=FALSE}
wC_r <- reactive({
  wc <- fread("output/wc.csv")
})

```


```{r echo=FALSE}
dataData <- reactive({
  results_all = resultsAll()
  # Filter one country
  data1 = results_all[results_all$one == input$country,]

  # Filter by tournament
  data2 = data1[data1$tournament == 'FIFA World Cup',]
  
  # Lethality per game
  data2$let_game = data2$score_1 - data2$score_2

})

```

```{r echo=FALSE}
dataDf <- reactive({

  data = dataData()
  wc = wC_r()
  # Count per year
  num_play = data.frame(table(data$year))
  names(num_play) <- c("year", "matches")

  # Total number of win games
  num_win = aggregate(. ~ year, data[,c("score_1","score_2","win", "year")], sum)

  # Merge total num_play with num_win
  num = merge(x = num_win, y = num_play, by = "year")

  # Create lethality ratio
  num$letality = num$score_1 - num$score_2
  num$win_proportion = num$win/num$matches

  # Create DF which includes all the years of World Cups
  df = merge(x = num, y = wc, by = "year", all.y = TRUE)
  # df[is.na(df)] <- 0
  df$year = as.character(df$year)
  # Column of Color
  col_col = c(rep(brewer.pal(9,"Set1"),times=2), brewer.pal(3,"Set1")[1:2])
  df2 = cbind(df, col_col)
})
```

```{r echo=FALSE}
dataLong <- reactive({
  df = dataDf()

  # Total number Vs. Total played
  df$match_g = df$matches - df$win
  part_1 = df[,c("year", "win")]
  names(part_1) <- c("year", "n_graph")
  part_1$control = c("Win")

  part_2 = df[,c("year", "match_g")]
  names(part_2) <- c("year", "n_graph")
  part_2$control = c("Matches")

  df_long1 <- rbind(part_1, part_2)
  df_long2 <- df_long1[order(df_long1$year), ]

})
```

Your team: 1930 - 2014
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r echo=FALSE}
# shiny inputs defined here
selectInput("country", label = "Country:",
            choices = c('Algeria', 'Angola', 'Argentina', 'Australia', 'Austria', 'Belgium', 'Bolivia', 'Bosnia-Herzegovina', 'Brazil', 'Bulgaria',
                        'Cameroon', 'Canada', 'Chile', 'China', 'Colombia', 'Congo DR', 'Costa Rica', 'Croatia', 'Cuba', 'Czech Republic', 'Czechoslovakia',
                        'Denmark', 'Ecuador', 'Egypt', 'El Salvador', 'England', 'France', 'German DR', 'Germany', 'Ghana', 'Greece', 'Haiti', 'Honduras',
                        'Hungary', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Korea DPR', 
                        'Korea Republic', 'Kuwait', 'Mexico', 'Morocco', 'Netherlands', 'New Zealand', 'Nigeria', 'Northern Ireland', 'Norway', 'Paraguay',
                        'Peru', 'Poland', 'Portugal', 'Romania', 'Russia', 'Saudi Arabia', 'Scotland', 'Senegal', 'Serbia', 'Slovakia', 'Slovenia', 
                        'South Africa', 'Spain', 'Sweden', 'Switzerland', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'USA', 'Ukraine', 
                        'United Arab Emirates', 'Uruguay', 'Wales', 'Yugoslavia'), selected = "Mexico")

# tags$head(tags$style(HTML(".selectize-input {height: 100px; width: 500px; font-size: 100px;}")))

```

<p align=center><font size=5.5>

<b> The World Cup is here again! </b>

</font>


<p align=justify><font size=4.8>

Let's review some interesting facts about our teams in all World Cups' history. 

1) The total number of matches of your team in all world cups.

2) Goal Average = scored goals - received goals. A number above one indicates that your team scores more goals than it receives. 

3) The matches of the world cup with the highest Goal Average.

4) The matches of the world cup with the lowest Goal Average.

</font></p>

&emsp;

<p>

The code and files are available here:
https://github.com/rodrigovaldes/world_cup

All data was compiled by Ágoston Török, available here, https://www.kaggle.com/agostontorok/soccer-world-cup-2018-winner/data
</p>



Row
-------------------------------------

### 1) Played and Won Games

```{r echo=FALSE}
renderPlot({
  df_long = dataLong()

  ggplot(data=df_long,aes(x=year, y=n_graph, fill=control)) +
    geom_bar(stat="identity",position ="stack") +
    blank_theme +
    labs(y = "Games", fill = " ") +
    theme(axis.text.x = element_text(face = 'bold', size = 12, angle = 90, vjust = 0.5),
      axis.text.y = element_text(size = 12, face = 'bold'),
      axis.title.x = element_blank(),
      axis.title.y = element_text(colour="grey20",size=14,face="bold"),
      legend.text = element_text(size = 13), 
      legend.position = "top") +
      scale_fill_manual(values=c('dodgerblue2','firebrick4')) +
      scale_color_manual(values=c('dodgerblue2','firebrick4'))
})
```

Row
-------------------------------------

### 2) Goal Average (Scored Goals - Received Goals)

```{r echo=FALSE}
# Graph Lethality Index an all World Cups
renderPlot({
  df = dataDf()
  col_col2 = c(rep(brewer.pal(9,"Set1"),times=2), brewer.pal(3,"Set1")[1:2])

  ggplot(data=df, aes(x=year, y=letality, fill=col_col)) +
  geom_bar(stat="identity")+
  blank_theme +
  scale_fill_manual("legend", values = col_col2) +
  labs(y = "Goal Average") +
  theme(axis.text.x = element_text(face = 'bold', size = 12, angle = 90, vjust = 0.5),
        axis.text.y = element_text(size = 12, face = 'bold'),
        legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_text(colour="grey20",size=14,face="bold")) +
  scale_x_discrete(breaks = df$year, labels = as.character(df$year))

})
```


### 3) Games of the World Cup with the highest Goal Average

```{r echo=FALSE}
# Print games of the best and worst World Cup
# Get the best lethality index

renderPrint({
  data = dataData()
  df = dataDf()
  max_let = max(df$letality[!is.na(df$letality)])

  # Year of the best World Cup for that country
  aux = get_year(df, max_let)

  # Games
  best_games = data[,c("date", "two", "score_1", "score_2")][which(data$year == aux),]
  names(best_games) <- c("Date", "Rival", "Goals!", "Goals Rival")

  print(best_games)

})

```

### 4) Testing

```{r}
# Max lethality all times
# 
# renderPrint({
#   data = dataData()
#   
#   # Get the lethality index of the best game
#   max_game = max(data$let_game[!is.na(data$let_game)])
#   
#   # Date of the best match
#   aux_game = get_date(df, max_game)
#   
#   # Game
#   best_game = data[,c("date", "two", "score_1", "score_2")][which(data$date == aux_game),]
#   names(best_game) <- c("Date", "Rival", "Goals!", "Goals Rival")
#   
#   print(best_game)
# })

```


### 5) Games of the World Cup with the lowest Goal Average

```{r echo=FALSE}
# Get the worst lethality index

renderPrint({
  data = dataData()
  df = dataDf()

  min_let = min(df$letality[!is.na(df$letality)])

  # Year of the worst World Cup for that country
  aux_2 = get_year(df, min_let)

  # Games
  worst_games = data[,c("date", "two", "score_1", "score_2")][which(data$year == aux_2),]
  names(worst_games) <- c("Date", "Rival", "Goals!", "Goals Rival")

  print(worst_games)
})
```


